version: "3.9"
services:
  app:
    image: nigel2392/netcache
    build:
      context: .
      # dockerfile: Dockerfile
    environment:
      PORT: 2392
      CACHE_DIR: /netcache/cache
      TIMEOUT: 300
      LOGFILE: /netcache/log/netcache.log
      LOGLEVEL: INFO
      MEMCACHE: false
    ports:
      - "2392:2392"
    volumes:
      - cache_data:/netcache/cache
      - ./log:/netcache/log
volumes:
  cache_data:

